scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 3
    max_angle: 177
    neighbors: 2
    window: 1
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_footprint
    min_x: -0.2
    max_x: 0.2
    min_y: -0.2
    max_y: 0.2
    min_z: -5.0
    max_z: 5.0
